jyx2/Assets/Jyx2Scenes/77_wanedao.unity, jyx2/Assets/Prefabs/Jyx2UI/ChatUIPanel.prefab, jyx2/Assets/Scripts/Jyx2UIScripts/ChatUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIData/ChatUIPanel_UIData.cs
=> 添加左右对话，添加名称显示

jyx2/Assets/Prefabs/Jyx2UI/MainUIPanel.prefab, jyx2/Assets/Scripts/Jyx2UIScripts/MainUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIData/MainUIPanel_UIData.cs
=> 优化了main UI panel 随显示按钮改变背景宽度

jyx2/Assets/Scripts/Jyx2UIScripts/MainUIPanel.cs, jyx2/Assets/Scripts/LevelMaster.cs
=> 修复战斗以及载入存档时不能传送到记录位置的问题

jyx2/Assets/Scripts/GameEventManager.cs, jyx2/Assets/Scripts/LevelMaster.cs
=> 修复事件触发时还能拖动人物的问题

jyx2/Assets/Jyx2Scenes/01_heluokezhan.unity, jyx2/Assets/Jyx2Scenes/03_youjiankezhan.unity, jyx2/Assets/Jyx2Scenes/40_yuelaikezhan.unity, jyx2/Assets/Jyx2Scenes/60_longmenkezhan.unity, jyx2/Assets/Jyx2Scenes/61_gaoshengkezhan.unity, jyx2/Assets/Scripts/BigMapZone.cs, jyx2/Assets/Scripts/Jyx2UIScripts/MainUIPanel.cs
=> 添加随机移动韦小宝逻辑

jyx2/Assets/Jyx2Scenes/13_mingjiaodidao.unity, jyx2/data/lua/jygame/ka274.lua, jyx2/data/lua/jygame/ka654.lua, jyx2/data/lua/jygame/ka688.lua, jyx2/data/lua/jygame/ka79.lua
删除部分脚本禁用trigger的部分
修正明教地道人物穿模以及事件对象绑定错误的问题
=> 撤销lua脚本禁用trigger的修改

jyx2/ProjectSettings/EditorBuildSettings.asset
=> 解决打出Window包无法跳转大地图的问题

jyx2/Assets/Jyx2Scenes/07_shandong.unity, jyx2/Assets/Scripts/LevelMaster.cs, jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs, jyx2/data/lua/jygame/ka390.lua, jyx2/data/lua/jygame/ka398.lua, jyx2/data/lua/jygame/ka701.lua
修改add3eventNum 接口实现
修改MovePlayer逻辑适配可以移动玩家以及其他物体
=> 修改add3eventnum接口实现逻辑，适配南贤北丑的系列提示脚本

jyx2/Assets/Jyx2Scenes/74_xiakedao.unity
刚刚发现部分新替换的模型离近了没有描边，不知道怎么改。。。不过不影响使用
侠客岛场景无法移动，不是我改出来的问题，我这边的版本就是动不了，通过编辑器移动主角已经测试侠客岛线逻辑通过
=> 修复灵蛇岛金花婆婆没动作的问题，侠客岛模型替换及动作调优

jyx2/Assets/Jyx2Scenes/09_chengkunju.unity, jyx2/Assets/Scripts/GameEventManager.cs, jyx2/Assets/Scripts/Jyx2UIScripts/BattleMainUIPanel.cs, jyx2/Assets/Scripts/LuaCore/LuaExecutor.cs, jyx2/data/lua/jygame/ka91.lua
=> 优化09_成昆居场景以及修复部分问题

jyx2/Assets/Editor/Jyx2MenuItems.cs
解决Android平台一键打包出错的问题
Issue195:#195
=> 解决Android平台一键打包出错的问题

jyx2/Assets/Jyx2Scenes/19_chongyanggong.unity, jyx2/data/lua/jygame/ka455.lua
=> 优化19_重阳宫场景

jyx2/Assets/Scripts/BigMapZone.cs
=> 填写这次提交更改的内容

jyx2/Assets/BuildSource/AnimationControllers/备份/周伯通Controller.controller, jyx2/Assets/BuildSource/AnimationControllers/备份/周伯通Controller.controller.meta, jyx2/Assets/Jyx2Scenes/07_shandong.unity, jyx2/Assets/Jyx2Scenes/20_baihuagu.unity, jyx2/data/lua/jygame/ka396.lua
=> 神雕侠侣剧情线——神雕山洞杨过动作问题修复+百花谷场景

jyx2/Assets/BuildSource/ModelCharacters/BattleNpc/明教弟子.prefab, jyx2/Assets/Jyx2Scenes/12_mingjiaofenduo.unity, jyx2/data/lua/jygame/ka76.lua, jyx2/data/lua/jygame/ka80.lua
=> 倚天屠龙记剧情线——明教分舵修正

jyx2/Assets/Scripts/Jyx2ResourceHelper.cs
[-]fix the building scripts compiler errors. #278
=> [*]pretty code.

jyx2/Assets/Jyx2Scenes/70_xiaoxiamiju.unity, jyx2/Assets/Scripts/BattleLoader.cs, jyx2/Assets/Scripts/GameConst.cs, jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs, jyx2/data/lua/main.lua
=> 增加最后武道大会触发事件

jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs, jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs, jyx2/Assets/Scripts/XiakePanelUI.cs
修改了一下选择武器按钮绑定的监听器的逻辑？装备的武器不再从运行时数据的键值对列表中删除，另外修改了filter，选择武器时会过滤掉已经装备的武器
=> #318 准备着装备时，haveitem会判断为false

jyx2/Assets/Prefabs/Jyx2UI/RoleItem.prefab, jyx2/Assets/Prefabs/Jyx2UI/XiakeUIPanel.prefab, jyx2/Assets/Scripts/BattleField/RangeLogic.cs, jyx2/Assets/Scripts/BattleManager/BattleManager.cs, jyx2/Assets/Scripts/GameConst.cs, jyx2/Assets/Scripts/Jyx2ItemUI.cs, jyx2/Assets/Scripts/Jyx2UIScripts/RoleUIItem.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIHelper.cs, jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs, jyx2/Assets/Scripts/Pojos/SavePojos/RoleInstance.cs, jyx2/Assets/Scripts/RuntimeData/GameRuntimeData.cs, jyx2/Assets/Scripts/XiakePanelUI.cs, jyx2/data/lua/jygame/ka297.lua, jyx2/data/lua/jygame/ka403.lua, jyx2/data/lua/jygame/ka494.lua
=> 修正直线和十字攻击特定方向无法受击的问题

jyx2/Assets/Scripts/Jyx2UIScripts/BagUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIData/BagUIPanel_UIData.cs, jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs
=> 尝试修复318，342，343

jyx2/Assets/Scripts/BattleLoader.cs, jyx2/Assets/Scripts/BattleManager/BattleManager.cs, jyx2/Assets/Scripts/Jyx2UIScripts/SelectRolePanel.cs
=> 修正战斗失败后传送问题，死亡角色选择问题

jyx2/Assets/Editor/Jyx2MenuItems.cs, jyx2/Assets/Scripts/Jyx2UIScripts/GameMainMenu.cs, jyx2/Assets/Scripts/Jyx2UIScripts/Jyx2_UIManager.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIData/GameMainMenu_UIData.cs
=> 游戏界面增加当前版本信息

jyx2/Assets/Prefabs/Jyx2UI/ChatUIPanel.prefab
=> 去掉对话界面奇怪的白色底色

jyx2/Assets/Scripts/GameUtil.cs, jyx2/Assets/Scripts/Jyx2UIScripts/SelectRolePanel.cs
=> 修复背包界面，选择使用物品，选择使用人时取消使用后，人物无法移动

jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs
=> 修复第二次以上入队会获得身上物品问题

jyx2/Assets/Prefabs/LevelMaster.prefab, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs
=> 修复上船和船穿模的问题

jyx2/Assets/Jyx2Scenes/03_youjiankezhan.unity, jyx2/Assets/Jyx2Scenes/09_chengkunju.unity, jyx2/Assets/Jyx2Scenes/11_guangmingding.unity, jyx2/Assets/Jyx2Scenes/26_heimuya.unity, jyx2/Assets/Jyx2Scenes/48_tiezhangshan.unity, jyx2/Assets/Jyx2Scenes/55_meizhuang.unity, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs, jyx2/Assets/Scripts/LevelMaster.cs, jyx2/data/lua/jygame/ka564.lua
=> 修正部分场景出口无法触发和船位置无法保存的问题

jyx2/Assets/Scripts/LevelMaster.cs
fix bug https://github.com/jynew/jynew/issues/447
=> fix bug https://github.com/jynew/jynew/issues/447

jyx2/Assets/Scripts/Pojos/SavePojos/RoleInstance.cs
修复问题https://github.com/jynew/jynew/issues/525
=> 修复人物在被攻击动画播放前就更新HP条的问题

jyx2/Assets/GeneralSettingsPanel.cs, jyx2/Assets/Jyx2Scenes/28_shaolinsi.unity, jyx2/Assets/Jyx2Scenes/52_yanziwu.unity, jyx2/Assets/Prefabs/Jyx2UI/GameOver.prefab
=> 修正洗髓经不消失和燕子坞没有关门的问题

jyx2/Assets/Scripts/Jyx2UIScripts/MainUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs, jyx2/Assets/Scripts/Pojos/SavePojos/RoleInstance.cs, jyx2/CreateTeamDebug.txt
=> 修复修炼逻辑及优化判断链

jyx2/Assets/Scripts/Jyx2UIScripts/BattleActionUIPanel.cs
=> 修复体力小于20无法移动的问题

jyx2/Assets/Jyx2Scenes/16_jinlunsi.unity, jyx2/Assets/Scripts/Pojos/SavePojos/RoleInstance.cs
=> 修正内功类升级时引用为空报错的问题

jyx2/Assets/Scripts/Jyx2UIScripts/MainUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIHelper.cs, jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs
=> 修复道具页面错误的显示“练出物品需经验”的问题

jyx2/Assets/BuildSource/Lua/jygame/ka37.lua, jyx2/Assets/BuildSource/Lua/jygame/ka38.lua
=> #486:对话在苏醒动画播放1.2秒后弹出。

jyx2/Assets/Scripts/BattleManager/AIManager.cs
=> 修复受伤程度等于100时，伤害除数等于0的问题

jyx2/Assets/Scripts/BattleLoader.cs, jyx2/Assets/Scripts/BattleManager/BattleManager.cs
=> 修复攻击伤害溢出后血量为负数的问题

jyx2/Assets/Scripts/Helpers/GameSettingManager.cs
Fix #761 #766
在安卓平台不进行任何分辨率设置，窗口/全屏设置无效。
这个问题我在模拟器中无法重现，手头也没有真机测试，还请哪位抽空打包测试一下🙏。
=> Fix #761 #766 尝试修复安卓平台上屏幕被压缩的问题

jyx2/Assets/Scripts/Jyx2Configs/GameConfigDatabase.cs, jyx2/Assets/Scripts/Jyx2ResourceHelper.cs, jyx2/Assets/Scripts/LuaCore/LuaManager.cs, jyx2/Assets/Scripts/MOD/MODLoader.cs
=> 修复资源找不到的问题

jyx2/Assets/BuildSource/Lua/jygame/ka102.lua, jyx2/Assets/Scripts/Jyx2UIScripts/BattleActionUIPanel.cs
=> 修复鼠标点击格子时移动无效的问题

jyx2/Assets/Scripts/BattleManager/InputManager.cs
=> 修复使用暗器穿透到格子的问题

jyx2/Assets/Scripts/BattleField/RangeLogic.cs, jyx2/Assets/Scripts/BattleManager/AIManager.cs, jyx2/Assets/Scripts/BattleManager/BattleManager.cs, jyx2/Assets/Scripts/Jyx2UIScripts/BattleActionUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/ShopUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs
…em is not the first item.
Fix xiake ui doesn't reset role position when have member left
=> 修复商店购买后选项复位问题，修复侠客离队后下一次移动至非临近位置问题。且修复战场移动和显示攻击点范围逻辑。

jyx2/Assets/Scripts/BattleManager/AIManager.cs, jyx2/Assets/Scripts/BattleManager/BattleLoop.cs, jyx2/Assets/Scripts/BattleManager/BattleManager.cs, jyx2/Assets/Scripts/GameSave/RoleInstance.cs
feat (AIManager.cs): 玩家控制的角色使用物品时，从背包获取；修改用药品的逻辑，提高自动战斗时候的存活率
to (BattleLoop.cs): 运动完之后记录当前回合生命值
to (BattleManager.cs): 初次加入战场时初始化上一回合生命值
to (RoleInstance): 增加上一回合生命值字段
#881
=> 自动模式下使用道具的逻辑的改进

jyx2/Assets/Scripts/Jyx2GameMap/BattleRole.cs
=> 修复金轮寺番僧攻击招式不断前进的问题

README.md
The version in the wiki also needs to be updated
=> up unity version

jyx2/Assets/Mods/SAMPLE/Maps/GameMaps/01_moqiaoshanzhuang.unity, jyx2/Assets/Mods/SAMPLE/ModelsResource/何云多/HeYunDuo.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/张云贤/ZhangYunXian.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/牛妞妞/NiuNiuNiu.fbx.meta, jyx2/Assets/Mods/SAMPLE/ModelsResource/牛妞妞/NiuNiuNiu.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/童四二/TongSiEr.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/粟兰/SuLan.fbx.meta, jyx2/Assets/Mods/SAMPLE/ModelsResource/粟兰/SuLan.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/莫穿林/moChuanLin.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/虚寂/XuJi.fbx.meta, jyx2/Assets/Mods/SAMPLE/ModelsResource/虚寂/XuJi.mat, jyx2/Assets/Mods/SAMPLE/ModelsResource/陶六一/TaoLiuYi.mat
=> 调整材质球（减少光污染）

jyx2/Assets/Scripts/SkilLEffects/RotateBlockParticles.cs, jyx2/Assets/Scripts/SkilLEffects/RotateBlockParticles.cs.meta, jyx2/Assets/Scripts/SkillCastHelper.cs, jyx2/Assets/VFX/EffectsPackage/EffectPackage/ArtRes/Effect/Prefabs/Skill-Direct-Red.prefab
=> 修复: 野球拳特效指向不正确的问题

jyx2/Assets/Prefabs/Jyx2UI/BagUIPanel.prefab, jyx2/Assets/Scripts/Jyx2UIScripts/BagUIPanel.cs
close #1091 
1. 交换下背包使用按钮与关闭按钮的顺序 。
2. 优化下背包代码，减少一些不必要的开销。
=> 优化: 背包按钮的交互使用

jyx2/Assets/Scripts/BattleManager/BattleManager.cs
=> 修复：修正一个武功等级常量的引用错误

jyx2/Assets/Prefabs/Jyx2UI/BattleMainUIPanel.prefab, jyx2/Assets/Scripts/Jyx2UIScripts/BattleMainUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/UIData/BattleMainUIPanel_UIData.cs
=> 优化: 战斗界面增加一个投降选项

jyx2/Assets/Prefabs/Player.prefab, jyx2/Assets/Scripts/CinemachineTriggerActionHelper.cs, jyx2/Assets/Scripts/JYX2DebugPanel.cs, jyx2/Assets/Scripts/Jyx2GameMap/GameEventManager.cs, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs, jyx2/Assets/Scripts/Jyx2UIScripts/InteractUIPanel.cs, jyx2/Assets/Scripts/Jyx2UIScripts/Jyx2_UIBase.cs, jyx2/Assets/Scripts/Jyx2UIScripts/MainUIPanel.cs, jyx2/Assets/Scripts/LevelMaster.cs, jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs, jyx2/Assets/Scripts/PlayerController.meta, jyx2/Assets/Scripts/PlayerController/PlayerLocomotionController.cs, jyx2/Assets/Scripts/PlayerController/PlayerLocomotionController.cs.meta
原有LevelMaster内容太杂，角色移动控制等代码耦合在里面，还有隐含时序问题
现在移动部分单独抽出放在PlayerLocomotionController.cs中，挂载在Jyx2Player下面作为子模块
另有一些Api优化
大量Get Set方法改为属性get set
IsPlayerCanControll()  -> playerControllable
=> 角色Locomotion模块重构，与LevelMaster剥离，优化API命名

jyx2/Assets/Scripts/MessageBox.cs
=> MessageBox涉及到Lua协程那边的调用，需要调整下逻辑

jyx2/Assets/Mods/SAMPLE/Prefabs/Player.prefab, jyx2/Assets/Prefabs/Player.prefab, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs, jyx2/Assets/Scripts/PlayerController/PlayerLocomotionController.cs
=> 修复拆分玩家逻辑后剧情寻路动画卡住的问题

jyx2/Assets/Scripts/GameSave/GameRuntimeData.cs
chore: 存档位置变更，兼容旧版本存档位置。
修改存档位置为Mod目录下的路径，同时默认mod存档也是一样。
兼容旧版本存档load路径
=> 存档位置变更，兼容旧版本存档位置

jyx2/Assets/Plugins/3rd/Reporter/Reporter.cs, jyx2/Assets/Scripts/GameStart.cs
1. release模式下锁死reporter的error窗口显示，免得有些玩家找不到。
2. 错误与异常触发时进行相关版本和时间信息的日志打印，方便追溯问题。
=> 优化: 日志功能优化

jyx2/Assets/Mods/JYX2/Lua/ka592.lua
=> 修回对话中被更改的地图坐标以适应新地图

jyx2/Assets/Scripts/Jyx2UIScripts/Jyx2_UIManager.cs
为UI框架新只能HideUI()扩展，增加代码可读性，降低负担
=> 扩展优化HideUI方法

jyx2/Assets/Mods/JYX2/Maps/GameMaps/1000_daditu.unity, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs, jyx2/Assets/Scripts/Jyx2GameMap/SecretNav.cs, jyx2/Assets/Scripts/Jyx2GameMap/SecretNav.cs.meta, jyx2/ProjectSettings/NavMeshAreas.asset
增加单独的导航区域，可以在指定入口进入，但禁止在远处通过自动寻路进入对应的隐秘区域。
=> 调整蝴蝶谷和神雕山洞的自动寻路

jyx2/Assets/Mods/JYX2/Maps/GameMaps/1000_daditu.unity
=> 大地图bug修复（蝴蝶谷）

jyx2/Assets/Prefabs/Jyx2UI/GameMainMenu.prefab, jyx2/Assets/Resources/RewiredInputManager.prefab, jyx2/Assets/Scripts/Battlebox/BattleboxHelper.cs, jyx2/Assets/Scripts/Jyx2GameMap/PlayerControl/Jyx2_PlayerInput.cs, jyx2/Assets/Scripts/Jyx2Input/Core/Context/UI/Jyx2Input_UIContext.cs, jyx2/Assets/Scripts/MOD/ModV2/GameModNative.cs, jyx2/Assets/Scripts/MOD/ModV2/UI/ModPanelNew.cs
* 修复native文件不存在导致游戏无法启动的问题（新拉的项目streamingAssets目录默认是空的）
* 修复未选择mod情况下点击启动导致数组越界的异常问题
* 修复主菜单头部按钮调整后手柄导航丢失的问题
=> Mod管理界面一些问题修复

jyx2/Assets/Scripts/BattleField/SkillCastInstance.cs, jyx2/Assets/Scripts/GameSave/GameRuntimeData.cs, jyx2/Assets/Scripts/GameUtil.cs, jyx2/Assets/Scripts/Jyx2Console.cs, jyx2/Assets/Scripts/Jyx2UIScripts/GameMainMenu.cs, jyx2/Assets/Scripts/Jyx2UIScripts/SystemUIPanel.cs, jyx2/Assets/Scripts/LevelMaster.cs, jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs, jyx2/Assets/Scripts/StoryEngine.cs
StoryEngine.DisplayPopInfo改为静态成员
=> 修改StoryEngine.DisplayPopInfo解决交互bug

jyx2/Assets/Mods/SAMPLE/Scripts/StoryPlayable.cs, jyx2/Assets/Scripts/GameUtil.cs, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs, jyx2/Assets/Scripts/Jyx2UIScripts/XiakeUIPanel.cs, jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs, jyx2/Assets/Scripts/StoryEngine.cs
=> StoryEngine修复交互bug

jyx2/Assets/0_GameStart.unity, jyx2/Assets/Prefabs/LevelMaster.prefab
=> 把StoryEngine改回LevelMaster

jyx2/Assets/3DScene/Model/Common/BuildingParts/Shinei/Materials/KZ_Guitai.mat
=> 高升客栈柜台描边减小

jyx2/Assets/Scripts/Jyx2UIScripts/GameMainMenu.cs
=> 修复: 新创角色错误沿用上一次名字缓存的问题

jyx2/Assets/Easy Save 3/Types/ES3UserType_WorldMapSaveData.cs, jyx2/Assets/Scripts/GameSave/GameRuntimeData.cs, jyx2/Assets/Scripts/GameSave/WorldMapSaveData.cs, jyx2/Assets/Scripts/Jyx2GameMap/Jyx2Player.cs
=> 大地图存档添加areaMask

jyx2/Assets/Scripts/LuaCore/Jyx2LuaBridge.cs
整理桥接函数文件
---只添加注释,整理代码布局,未修改方法的定义
=> 更新 Jyx2LuaBridge.cs

jyx2/Assets/Scripts/Jyx2GameMap/PlayerControl/Jyx2_PlayerMovement.cs
=> Revert "修复：在自动导航碰到Npc之后一直播放跑步动画的问题"
